arch: linear
aug: true
augmentation: RandomResizedCrop
batch_size: 4096
ckpt: ''
ckpt_iter: -1
config_file: null
data: imagenet100
dist: dp
dist_address: ''
encode_layer: h
encoder_ckpt: 'imagenet100_mmcl_pgd.pth.tar'
eval_freq: 100
finetune: false
iters: 3902
log_freq: 1000
lr: 1.6
lr_schedule: linear
model_id: -1
name: eval_imagenet_newmodels
node_rank: 0
opt: sgd
precompute_emb_bs: 100
problem: eval
save_freq: 10000000000000000
scale_lower: 0.08
seed: -1
test_bs: 4096
tmp: false
warmup: 0.0
weight_decay: 0.0
workers: 8
world_size: 1