arch: ResNet50
aug: true
batch_size: 256
# batch_size: 256
ckpt: ''
color_dist_s: 1.0
config_file: ''
data: imagenet
dist: ddp
# dist: dp
dist_address: '127.0.0.1:1230'
eval_freq: 50040
gpu: 0
iters: 500400
log_freq: 100
lr: 1.2
lr_schedule: warmup-anneal
multiplier: 2
name: imagenet-reproduce
node_rank: 0
opt: lars
problem: mmcl_pgd
root: ''
save_freq: 12510
scale_lower: 0.08
seed: -1
sync_bn: true
temperature: 0.1
tmp: false
verbose: true
warmup: 0.1
weight_decay: 1.0e-06
workers: 8
# workers: 1
world_size: 1
C: -1
kernel_type: 'rbf'
sigma: 10.0
reg: 0.1
num_iters: 1000
eta: 1e-3
stop_condition: 1e-2
solver_type: nesterov
use_norm: false